spring.application.name=transaction-exchange-service
server.servlet.context-path=/wex/v1

# Set the active profile here (dev, qa, or prod).
# You can also pass this as a command line argument when starting the jar:
# java -jar your-app.jar --spring.profiles.active=prod
spring.profiles.active=dev

# Common Properties
treasury.api.url=https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange
